spring.application.name=config-server
server.port=0

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configurations/

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.instance-info-replication-interval-seconds=5
