spring.application.name=discovery-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.server.use-read-only-response-cache=false
eureka.server.response-cache-update-interval-ms=1000
eureka.server.eviction-interval-timer-in-ms=5000
