CREATE TABLE participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP,
    event_id BIGINT,
    requester_id BIGINT,
    status VARCHAR(32),
    CONSTRAINT uq_request_requester_event UNIQUE (requester_id, event_id)
);

CREATE INDEX idx_requests_event_status ON participation_requests (event_id, status);
CREATE INDEX idx_requests_requester_id ON participation_requests (requester_id);
