server.port=${COLLECTOR_HTTP_PORT:9191}
grpc.server.port=0

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=ru.practicum.ewm.stats.avro.serialization.AvroSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
collector.kafka.user-actions-topic=${USER_ACTIONS_TOPIC:stats.user-actions.v1}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.level.ru.practicum=INFO

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.instance-info-replication-interval-seconds=5
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.client.registry-fetch-interval-seconds=5
