server.port=8080

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=main-service-api
spring.cloud.gateway.routes[0].uri=lb://main-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/admin/**,/users/**,/categories/**,/events/**,/compilations/**,/comments/**
spring.cloud.gateway.routes[0].filters[0].name=Retry
spring.cloud.gateway.routes[0].filters[0].args.retries=3
spring.cloud.gateway.routes[0].filters[0].args.statuses=SERVICE_UNAVAILABLE
spring.cloud.gateway.routes[0].filters[0].args.methods=GET,POST,PUT,PATCH,DELETE
spring.cloud.gateway.routes[0].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[0].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[0].filters[0].args.backoff.factor=2
