server.port=0

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ewm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ewm}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.instance-info-replication-interval-seconds=5

stats.server.url=${STATS_SERVER_URL:http://stats-server}
