spring.application.name=gateway-server
spring.config.import=configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=12
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.client.registry-fetch-interval-seconds=5
