CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    created_on TIMESTAMP NOT NULL,
    event_date TIMESTAMP NOT NULL,
    published_on TIMESTAMP,
    state VARCHAR(32) NOT NULL,
    lat REAL,
    lon REAL,
    confirmed_requests INTEGER NOT NULL DEFAULT 0,
    views BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_events_initiator_id ON events (initiator_id);
CREATE INDEX idx_events_category_id ON events (category_id);
CREATE INDEX idx_events_state_event_date ON events (state, event_date);
